// Copyright 1999 Association for Universities for Research in Astronomy, Inc.,
// Observatory Control System, Gemini Telescopes Project.
// See the file LICENSE for complete details.
//
// $Id: SPNestedChange.java 46831 2012-07-18 22:22:12Z rnorris $
//

package edu.gemini.pot.sp;

import java.beans.PropertyChangeEvent;


/**
 * <code>SPNestedChange</code> serves as the base class for structure and
 * composite change events.  Each of these event types have the common feature
 * that they may be generated by a nested component.
 * <code>{@link SPStructureChange}</code> and
 * <code>{@link SPCompositeChange}</code> extend this class to create two
 * distinct types, but (at this time) add no additional features.
 *
 * <p>This class encapsulates the original source of the change event (the
 * actual node that has changed) the property of that node that was effected,
 * and the old and new values of the property.
 */
public class SPNestedChange extends PropertyChangeEvent {

    /**
     * Constructs with the property name that changed, the node that was directly
     * changed, and the new value of the property.
     */
    protected SPNestedChange(
            String propName,
            ISPNode node,
            Object oldValue,
            Object newValue) {
        super(node, propName, oldValue, newValue);
    }

    public ISPNode getModifiedNode() {
        return (ISPNode) getSource();
    }

}

