#ifndef DATAUTIL_H_
#define DATAUTIL_H_

#include <giapi/giapi.h>

namespace giapi {

class DataUtil {
public:

	/**
	 * Send an observation event associated to the given datalabel to the 
	 * GMP. 
	 * This method should be called by the instrument at each phase of the 
	 * execution of an observe sequence command. 
	 * 
	 * @param event The observation event to be sent, such as 
	 *              data::OBS_START_ACQ 
	 * @param datalabel the data-label that is being generated by the 
	 *                  observe command.  
	 * 
	 * @return status::OK if the event was dispatched properly or 
	 *         status::ERROR if there is a problem. 
	 */
	static int postObservationEvent(data::ObservationEvent event,
			const char * datalabel);

	/**
	 * Send an ancillary file event associated to the given datalabel 
	 * to the GMP.
	 * 
	 * @param filename name of the ancillary file  
	 * @param datalabel the data-label generated by an observe sequence 
	 *        command that will be associated to this ancillary file
	 *
	 * @return status::OK if the event was dispatched properly or 
	 *         status::ERROR if there is a problem. 
	 */
	static int postAncillaryFileEvent(const char * filename,
			const char * datalabel);
	/**
	 * Send an intermediate file event associated to the given datalabel 
	 * to the GMP and with the given hint.
	 * 
	 * @param filename name of the intermediate file  
	 * @param datalabel the data-label generated by an observe sequence 
	 *        command that will be associated to this intermediate file
	 * @param hint hint The hint can be used to indicate different types 
	 *        of intermediate files and is instrument dependant.
	 * @return status::OK if the event was dispatched properly or 
	 *         status::ERROR if there is a problem. 
	 */
	static int postIntermediateFileEvent(const char * filename,
			const char * datalabel, const char * hint);

private:
	DataUtil();
	virtual ~DataUtil();
};

}

#endif /*DATAUTIL_H_*/
