//
// $Id: ConfigProducer.java 5899 2005-03-15 22:05:53Z shane $
//
package edu.gemini.spModel.obsseq;

import java.io.Serializable;

/**
 * A ConfigProducer marks a generator of configuration information.
 * ConfigProducer implementations may be concerned with a single related set of
 * items, such as telescope offset positions, or may be concerned with a
 * complex hierarchy of child producers like {@link Sequence}.
 */
public interface ConfigProducer extends Serializable {

    /**
     * How many distinct steps, configuration changes, are generated by this
     * producer.
     */
    int getStepCount();

    /**
     * Retrieves the keys of the items whose values are changed by this
     * producer.
     */
    //ItemKey[] getIteratedKeys();

    /**
     * Obtains a ConfigMerger to be used in the process of constructing a
     * {@link edu.gemini.spModel.config2.ConfigSequence}.
     */
    ConfigMerger getConfigMerger();
}
